/**
 * Typed access layer over the AI detection replay datasets.
 *
 * One dataset per processed recording:
 *   - 'survey'       — Sanjay Lake four-clip park survey (sanjayLakeReplay.json)
 *   - 'construction' — Sanjay Lake works-zone clip       (sanjayLakeConstructionReplay.json)
 *   - 'lala-1'..'lala-3'             — Lala Hardeval, one dataset per clip
 *   - 'asaf-1'..'asaf-2'             — R Block Asaf Ali, one dataset per clip
 *   - 'vasant-1'..'vasant-2'         — Vasant Udyan, one dataset per clip
 *   - 'smriti-van-1'..'smriti-van-4' — Smriti Van, one dataset per clip; the app
 *                      chains the four so they read as one continuous survey.
 *
 * All share the same tuple layout (generated by tools/convert-report.py,
 * tools/convert-construction.js and tools/convert-smriti.js). Exactly one dataset
 * is "active" at a time; `setActiveReplay(id)` swaps it, and because the switched
 * exports are live bindings, every subscribed screen recomputes from the new
 * dataset on its next render. This module is the only place that knows the tuple
 * layout.
 */
import surveyRaw from '../data/sanjayLakeReplay.json';
import constructionRaw from '../data/sanjayLakeConstructionReplay.json';
import smritiVan1Raw from '../data/smritiVanClip1Replay.json';
import smritiVan2Raw from '../data/smritiVanClip2Replay.json';
import smritiVan3Raw from '../data/smritiVanClip3Replay.json';
import smritiVan4Raw from '../data/smritiVanClip4Replay.json';
import lala1Raw from '../data/lalaHardevalClip1Replay.json';
import lala2Raw from '../data/lalaHardevalClip2Replay.json';
import lala3Raw from '../data/lalaHardevalClip3Replay.json';
import asaf1Raw from '../data/asafAliClip1Replay.json';
import asaf2Raw from '../data/asafAliClip2Replay.json';
import vasant1Raw from '../data/vasantUdyanClip1Replay.json';
import vasant2Raw from '../data/vasantUdyanClip2Replay.json';
import vatika1Raw from '../data/vasantVatikaClip1Replay.json';
import vatika2Raw from '../data/vasantVatikaClip2Replay.json';
import vatika3Raw from '../data/vasantVatikaClip3Replay.json';

export type ScoreKey =
  | 'overall'
  | 'green'
  | 'plantation'
  | 'lawnScore'
  | 'cleanliness'
  | 'irrigation'
  | 'infrastructure'
  | 'safety';

export type CoverageKey =
  | 'greenCover'
  | 'canopy'
  | 'lawn'
  | 'bareGround'
  | 'dryVeg'
  | 'debris'
  | 'stems'
  | 'waterSurface'
  | 'algalShare'
  | 'exposedBed'
  | 'paved'
  | 'waterlogging';

export type TimelineKey = 't' | 'detections' | ScoreKey | CoverageKey;

export type DetectionClass = {
  index: number;
  name: string;
  code: string;
  category: string;
  subParameter: string;
};

export type ActiveDetection = {
  className: string;
  code: string;
  condition: number | null;
  confidence: number | null;
  isDefect: boolean;
};

export type DetectionGroup = {
  className: string;
  code: string;
  count: number;
  meanCondition: number | null;
  hasDefect: boolean;
};

export type Anomaly = {
  Priority: string;
  'Track ID': string;
  'DTU code': string;
  Anomaly: string;
  'DTU sub-parameter': string;
  Severity: string;
  'Condition %': string;
  'First seen (s)': string;
  'Last seen (s)': string;
  'Peak area (px)': string;
  'Suggested action': string;
};

export type Recommendation = {
  '#': string;
  Priority: string;
  'DTU category': string;
  Finding: string;
  'Recommended action': string;
  Owner: string;
};

type Aggregate = { mean: number; min: number; max: number };

export type ReplayEvent = {
  time: number;
  type: 'warning' | 'error' | 'info';
  title: string;
  message: string;
};

export type ClipBound = { clip: string; zone: string; start: number; end: number };

type TrackRow = { cls: string; first: number; cond: number | null };

/** Everything derived from one dataset JSON. */
type Dataset = ReturnType<typeof buildDataset>;

// [time, [[classIndex, condition, confidence, isDefect], ...]]
type DetectionEntry = [number, (number | null)[][]];

function buildDataset(raw: any) {
  const fields = raw.timelineFields as TimelineKey[];
  const timeline = raw.timeline as number[][];
  const times = timeline.map((row) => row[0]);
  const idx = fields.reduce<Record<string, number>>((acc, key, i) => {
    acc[key] = i;
    return acc;
  }, {});
  const classes = raw.detectionClasses as DetectionClass[];
  const detections = raw.detections as DetectionEntry[];
  return {
    fields,
    timeline,
    times,
    idx,
    classes,
    classByIndex: new Map(classes.map((c) => [c.index, c])),
    detections,
    detectionTimes: detections.map((d) => d[0]),
    zones: (raw.zones ?? []) as string[],
    tracks: (raw.tracks ?? []) as TrackRow[],
    duration: times[times.length - 1] as number,
    meta: raw.meta as Record<string, string | number>,
    headlineFindings: raw.headlineFindings as string[],
    anomalies: raw.anomalies as unknown as Anomaly[],
    recommendations: raw.recommendations as unknown as Recommendation[],
    categoryA: raw.categoryA as Record<string, string | number>[],
    categoryB: raw.categoryB as Record<string, string | number>[],
    classRollup: raw.classRollup as Record<
      string,
      { count: number; meanCondition: number | null; worstCondition: number | null }
    >,
    events: (raw.events ?? []) as ReplayEvent[],
    clips: (raw.clips ?? []) as ClipBound[],
    summary: raw.summary as {
      scores: Record<ScoreKey, Aggregate>;
      coverage: Record<CoverageKey, Aggregate>;
    },
  };
}

export type ReplayId =
  | 'survey'
  | 'construction'
  | 'smriti-van-1'
  | 'smriti-van-2'
  | 'smriti-van-3'
  | 'smriti-van-4'
  | 'lala-1'
  | 'lala-2'
  | 'lala-3'
  | 'asaf-1'
  | 'asaf-2'
  | 'vasant-1'
  | 'vasant-2'
  | 'vatika-1'
  | 'vatika-2'
  | 'vatika-3';

const DATASETS: Record<ReplayId, Dataset> = {
  survey: buildDataset(surveyRaw),
  construction: buildDataset(constructionRaw),
  'smriti-van-1': buildDataset(smritiVan1Raw),
  'smriti-van-2': buildDataset(smritiVan2Raw),
  'smriti-van-3': buildDataset(smritiVan3Raw),
  'smriti-van-4': buildDataset(smritiVan4Raw),
  'lala-1': buildDataset(lala1Raw),
  'lala-2': buildDataset(lala2Raw),
  'lala-3': buildDataset(lala3Raw),
  'asaf-1': buildDataset(asaf1Raw),
  'asaf-2': buildDataset(asaf2Raw),
  'vasant-1': buildDataset(vasant1Raw),
  'vasant-2': buildDataset(vasant2Raw),
  'vatika-1': buildDataset(vatika1Raw),
  'vatika-2': buildDataset(vatika2Raw),
  'vatika-3': buildDataset(vatika3Raw),
};

const DEFAULT_REPLAY_ID: ReplayId = 'survey';

// The active dataset and the live-binding exports derived from it. Reassigned as
// a unit by setActiveReplay so importers (which hold live bindings) see the swap.
let active: Dataset = DATASETS[DEFAULT_REPLAY_ID];

export let activeReplayId: ReplayId = DEFAULT_REPLAY_ID;
export let replayMeta = active.meta;
export let headlineFindings = active.headlineFindings;
export let anomalies = active.anomalies;
export let recommendations = active.recommendations;
export let categoryA = active.categoryA;
export let categoryB = active.categoryB;
export let classRollup = active.classRollup;
/** In-app alerts to raise as playback crosses notable findings (empty for some clips). */
export let replayEvents = active.events;
/** The concatenated survey clips (or the single works-zone clip) on the global clock. */
export let clips = active.clips;
export let clipSummary = active.summary;
/** Total length of the active clip, in seconds. */
export let REPLAY_DURATION = active.duration;

/** Switch which recording the whole app reads from. */
export function setActiveReplay(id: ReplayId): void {
  if (!DATASETS[id]) return;
  active = DATASETS[id];
  activeReplayId = id;
  replayMeta = active.meta;
  headlineFindings = active.headlineFindings;
  anomalies = active.anomalies;
  recommendations = active.recommendations;
  categoryA = active.categoryA;
  categoryB = active.categoryB;
  classRollup = active.classRollup;
  replayEvents = active.events;
  clips = active.clips;
  clipSummary = active.summary;
  REPLAY_DURATION = active.duration;
}

/**
 * The burned-in overlay on the source video smooths its sub-scores over roughly
 * one second while printing coverage percentages instantaneously. Matching that
 * window keeps the app's figures identical to the numbers visible in the video,
 * and incidentally stops the readouts jittering at the 15 Hz sample rate.
 */
export const SCORE_SMOOTHING_SEC = 1.0;

/** Index of the last sample at or before `t`. Clamped to the array bounds. */
function indexAt(times: number[], t: number): number {
  if (t <= times[0]) return 0;
  if (t >= times[times.length - 1]) return times.length - 1;
  let lo = 0;
  let hi = times.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (times[mid] <= t) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

/** Raw instantaneous value of a single field at time `t`. */
export function valueAt(field: TimelineKey, t: number): number {
  return active.timeline[indexAt(active.times, t)][active.idx[field]];
}

/** Trailing mean of `field` over `windowSec` ending at `t`. */
export function smoothedValueAt(field: TimelineKey, t: number, windowSec = SCORE_SMOOTHING_SEC): number {
  const times = active.times;
  const timeline = active.timeline;
  const end = indexAt(times, t);
  const col = active.idx[field];
  const from = t - windowSec;
  let sum = 0;
  let n = 0;
  for (let i = end; i >= 0 && times[i] >= from; i -= 1) {
    sum += timeline[i][col];
    n += 1;
  }
  return n === 0 ? timeline[end][col] : sum / n;
}

export type ReplayFrame = {
  time: number;
  detections: number;
  scores: Record<ScoreKey, number>;
  coverage: Record<CoverageKey, number>;
};

const SCORE_KEYS: ScoreKey[] = [
  'overall',
  'green',
  'plantation',
  'lawnScore',
  'cleanliness',
  'irrigation',
  'infrastructure',
  'safety',
];

const COVERAGE_KEYS: CoverageKey[] = [
  'greenCover',
  'canopy',
  'lawn',
  'bareGround',
  'dryVeg',
  'debris',
  'stems',
  'waterSurface',
  'algalShare',
  'exposedBed',
  'paved',
  'waterlogging',
];

/** Zone (survey clip) label at time `t`. */
export function zoneAt(t: number): string {
  return active.zones[indexAt(active.times, t)] ?? '';
}

/**
 * Everything the dashboard needs for a single instant: smoothed scores (to match
 * the video overlay) and instantaneous coverage percentages.
 */
export function frameAt(t: number): ReplayFrame {
  const i = indexAt(active.times, t);
  const row = active.timeline[i];

  const scores = {} as Record<ScoreKey, number>;
  for (const key of SCORE_KEYS) scores[key] = smoothedValueAt(key, t);

  const coverage = {} as Record<CoverageKey, number>;
  for (const key of COVERAGE_KEYS) coverage[key] = row[active.idx[key]];

  return {
    time: row[0],
    detections: row[active.idx.detections],
    scores,
    coverage,
  };
}

/** Individual detections logged at the sampled instant nearest to `t`. */
export function detectionsAt(t: number): ActiveDetection[] {
  const entry = active.detections[indexAt(active.detectionTimes, t)];
  if (!entry) return [];
  return entry[1].map((d) => {
    const cls = active.classByIndex.get(d[0] as number);
    return {
      className: cls?.name ?? 'Unknown',
      code: cls?.code ?? '',
      condition: d[1],
      confidence: d[2],
      isDefect: d[3] === 1,
    };
  });
}

/** Detections at `t`, collapsed to one row per class — the "detected in this frame" panel. */
export function detectionGroupsAt(t: number): DetectionGroup[] {
  const groups = new Map<string, { code: string; conds: number[]; count: number; defect: boolean }>();
  for (const d of detectionsAt(t)) {
    const g = groups.get(d.className) ?? { code: d.code, conds: [], count: 0, defect: false };
    g.count += 1;
    g.defect = g.defect || d.isDefect;
    if (d.condition !== null) g.conds.push(d.condition);
    groups.set(d.className, g);
  }
  return Array.from(groups.entries())
    .map(([className, g]) => ({
      className,
      code: g.code,
      count: g.count,
      meanCondition: g.conds.length
        ? Math.round((g.conds.reduce((a, b) => a + b, 0) / g.conds.length) * 10) / 10
        : null,
      hasDefect: g.defect,
    }))
    .sort((a, b) => b.count - a.count || a.className.localeCompare(b.className));
}

/** Anomalies whose tracked lifetime has begun by time `t`, worst first. */
export function anomaliesUpTo(t: number): Anomaly[] {
  return active.anomalies.filter((a) => Number(a['First seen (s)']) <= t);
}

/**
 * Number of distinct tracked objects of each class whose track has begun by `t`.
 * These grow as the survey plays — an asset the drone has flown over is "found".
 */
export function cumulativeCountsUpTo(t: number): Record<string, number> {
  const out: Record<string, number> = {};
  for (const tr of active.tracks) {
    if (tr.first <= t) out[tr.cls] = (out[tr.cls] ?? 0) + 1;
  }
  return out;
}

/** Mean condition of a class across tracks found by `t` (null if none yet). */
export function meanConditionUpTo(cls: string, t: number): number | null {
  let sum = 0;
  let n = 0;
  for (const tr of active.tracks) {
    if (tr.first <= t && tr.cond !== null) {
      sum += tr.cond;
      n += 1;
    }
  }
  return n ? Math.round((sum / n) * 10) / 10 : null;
}

/** Sparkline source: `field` sampled at a fixed number of points up to `t`. */
export function seriesUpTo(field: TimelineKey, t: number, points = 48): number[] {
  const end = indexAt(active.times, t);
  if (end <= 0) return [active.timeline[0][active.idx[field]]];
  const step = Math.max(1, Math.floor(end / points));
  const out: number[] = [];
  for (let i = 0; i <= end; i += step) out.push(active.timeline[i][active.idx[field]]);
  return out;
}

export const scoreLabels: Record<ScoreKey, string> = {
  overall: 'Overall Park Health',
  green: 'Green Cover',
  plantation: 'Plantation Health',
  lawnScore: 'Lawn Quality',
  cleanliness: 'Cleanliness',
  irrigation: 'Irrigation Efficiency',
  infrastructure: 'Infrastructure',
  safety: 'Safety',
};

export const coverageLabels: Record<CoverageKey, string> = {
  greenCover: 'Green cover',
  canopy: 'Tree canopy',
  lawn: 'Lawn cover',
  bareGround: 'Bare ground',
  dryVeg: 'Dry vegetation',
  debris: 'Ground debris',
  stems: 'Trees in view',
  waterSurface: 'Water surface',
  algalShare: 'Algal share',
  exposedBed: 'Exposed bed',
  paved: 'Paved area',
  waterlogging: 'Waterlogging',
};
