/**
 * Every finding the AI raised across the seven surveyed parks, with the place
 * it was raised.
 *
 * Generated by tools/build-anomalies.js — do not edit by hand. The wording is
 * the same text the app raises as a notification during playback, so a finding
 * reads identically whether it is met live or looked up here afterwards.
 *
 * `frame` is a still pulled from the survey recording at `time`, which is why
 * the picture always shows the thing the words describe.
 *
 * Coordinates are approximate: they were read off marker positions on satellite
 * imagery, not recorded by the aircraft, so they locate a finding to within a
 * few metres rather than pinpointing it.
 */
import { ANOMALY_FRAMES } from './anomalyFrames';

export type AnomalySeverity = 'info' | 'warning' | 'error';

export type Anomaly = {
  id: string;
  parkId: string;
  /** Position within its park's list, as printed in the survey document. */
  index: number;
  /** Seconds into the park's recording. */
  time: number;
  /** Which clip of the survey, 1-based. */
  clip: number;
  type: AnomalySeverity;
  title: string;
  message: string;
  lat: number;
  lng: number;
  mapUrl: string;
};

export const ANOMALIES: Anomaly[] = [
  {
    "id": "rohini-dda-1",
    "parkId": "rohini-dda",
    "index": 1,
    "time": 5,
    "clip": 1,
    "type": "info",
    "title": "Hedges need a trim",
    "message": "Hedge beds looking uneven along the edges — a trim would tidy things up.",
    "lat": 28.722542,
    "lng": 77.117856,
    "mapUrl": "https://www.google.com/maps?q=28.722542,77.117856"
  },
  {
    "id": "rohini-dda-2",
    "parkId": "rohini-dda",
    "index": 2,
    "time": 15,
    "clip": 1,
    "type": "warning",
    "title": "Bare patches on the lawn",
    "message": "Patches of bare ground showing through the lawn — needs replanting.",
    "lat": 28.721921,
    "lng": 77.119036,
    "mapUrl": "https://www.google.com/maps?q=28.721921,77.119036"
  },
  {
    "id": "rohini-dda-3",
    "parkId": "rohini-dda",
    "index": 3,
    "time": 4,
    "clip": 2,
    "type": "warning",
    "title": "Lake water looking murky",
    "message": "Water quality appears poor — greenish tinge suggests algae buildup.",
    "lat": 28.720039,
    "lng": 77.117384,
    "mapUrl": "https://www.google.com/maps?q=28.720039,77.117384"
  },
  {
    "id": "rohini-dda-4",
    "parkId": "rohini-dda",
    "index": 4,
    "time": 15,
    "clip": 2,
    "type": "info",
    "title": "Shoreline needs cleanup",
    "message": "Debris visible along the lake edge — clearing would improve the look.",
    "lat": 28.719475,
    "lng": 77.118178,
    "mapUrl": "https://www.google.com/maps?q=28.719475,77.118178"
  },
  {
    "id": "rohini-dda-5",
    "parkId": "rohini-dda",
    "index": 5,
    "time": 23,
    "clip": 2,
    "type": "error",
    "title": "Floating waste in the lake",
    "message": "Waste floating on the surface — needs immediate skimming and cleanup.",
    "lat": 28.719212,
    "lng": 77.117813,
    "mapUrl": "https://www.google.com/maps?q=28.719212,77.117813"
  },
  {
    "id": "rohini-dda-6",
    "parkId": "rohini-dda",
    "index": 6,
    "time": 5,
    "clip": 3,
    "type": "warning",
    "title": "Algae spreading in the channel",
    "message": "Green algae coating the channel surface — water circulation needed.",
    "lat": 28.718384,
    "lng": 77.119187,
    "mapUrl": "https://www.google.com/maps?q=28.718384,77.119187"
  },
  {
    "id": "rohini-dda-7",
    "parkId": "rohini-dda",
    "index": 7,
    "time": 18,
    "clip": 3,
    "type": "warning",
    "title": "Bank erosion visible",
    "message": "Channel banks wearing away in spots — could use reinforcement.",
    "lat": 28.717857,
    "lng": 77.11983,
    "mapUrl": "https://www.google.com/maps?q=28.717857,77.119830"
  },
  {
    "id": "rohini-dda-8",
    "parkId": "rohini-dda",
    "index": 8,
    "time": 30,
    "clip": 3,
    "type": "info",
    "title": "Some litter near the banks",
    "message": "Loose debris along the channel edge — a cleanup would help.",
    "lat": 28.717556,
    "lng": 77.1188,
    "mapUrl": "https://www.google.com/maps?q=28.717556,77.118800"
  },
  {
    "id": "rohini-dda-9",
    "parkId": "rohini-dda",
    "index": 9,
    "time": 42,
    "clip": 3,
    "type": "warning",
    "title": "Dry patches along the bank",
    "message": "Plant cover thinning on the banks — watering and replanting needed.",
    "lat": 28.717367,
    "lng": 77.119573,
    "mapUrl": "https://www.google.com/maps?q=28.717367,77.119573"
  },
  {
    "id": "sanjay-lake-1",
    "parkId": "sanjay-lake",
    "index": 1,
    "time": 45,
    "clip": 1,
    "type": "warning",
    "title": "Waterlogging detected",
    "message": "Standing water in the children's play area — investigate drainage.",
    "lat": 28.615101,
    "lng": 77.28619,
    "mapUrl": "https://www.google.com/maps?q=28.615101,77.286190"
  },
  {
    "id": "sanjay-lake-2",
    "parkId": "sanjay-lake",
    "index": 2,
    "time": 55,
    "clip": 1,
    "type": "warning",
    "title": "Dry patches on the lawn",
    "message": "Dry, stressed turf visible across the play area lawn — irrigation check needed.",
    "lat": 28.614794,
    "lng": 77.287409,
    "mapUrl": "https://www.google.com/maps?q=28.614794,77.287409"
  },
  {
    "id": "sanjay-lake-3",
    "parkId": "sanjay-lake",
    "index": 3,
    "time": 93,
    "clip": 1,
    "type": "warning",
    "title": "Dry vegetation flagged",
    "message": "2–3 trees showing dry, stressed canopy — schedule irrigation and inspection.",
    "lat": 28.615417,
    "lng": 77.289478,
    "mapUrl": "https://www.google.com/maps?q=28.615417,77.289478"
  },
  {
    "id": "sanjay-lake-4",
    "parkId": "sanjay-lake",
    "index": 4,
    "time": 147,
    "clip": 1,
    "type": "warning",
    "title": "Bare patches spreading",
    "message": "Bare, compacted ground along the pathway — re-turfing and decompaction recommended.",
    "lat": 28.614579,
    "lng": 77.291281,
    "mapUrl": "https://www.google.com/maps?q=28.614579,77.291281"
  },
  {
    "id": "sanjay-lake-5",
    "parkId": "sanjay-lake",
    "index": 5,
    "time": 167,
    "clip": 1,
    "type": "warning",
    "title": "Construction debris on footbridge",
    "message": "Construction debris detected on the footbridge — clear the site and verify safety barriers.",
    "lat": 28.615362,
    "lng": 77.293296,
    "mapUrl": "https://www.google.com/maps?q=28.615362,77.293296"
  },
  {
    "id": "sanjay-lake-6",
    "parkId": "sanjay-lake",
    "index": 6,
    "time": 185.5,
    "clip": 1,
    "type": "warning",
    "title": "Construction debris on the pathway",
    "message": "Rubble and broken brick piled directly on the walking track — clear the route and barricade the works area.",
    "lat": 28.614896,
    "lng": 77.294304,
    "mapUrl": "https://www.google.com/maps?q=28.614896,77.294304"
  },
  {
    "id": "lala-harydal-1",
    "parkId": "lala-harydal",
    "index": 1,
    "time": 5,
    "clip": 1,
    "type": "warning",
    "title": "Bare patches showing",
    "message": "Ground cover thinning under the palm avenue — could use re-turfing.",
    "lat": 28.540049,
    "lng": 77.283572,
    "mapUrl": "https://www.google.com/maps?q=28.540049,77.283572"
  },
  {
    "id": "lala-harydal-2",
    "parkId": "lala-harydal",
    "index": 2,
    "time": 18,
    "clip": 1,
    "type": "info",
    "title": "Some litter about",
    "message": "A bit of loose debris across the lawns — a sweep would tidy it up.",
    "lat": 28.539841,
    "lng": 77.28413,
    "mapUrl": "https://www.google.com/maps?q=28.539841,77.284130"
  },
  {
    "id": "lala-harydal-3",
    "parkId": "lala-harydal",
    "index": 3,
    "time": 60,
    "clip": 1,
    "type": "warning",
    "title": "More bare patches ahead",
    "message": "Bare ground expanding along the far end of the avenue — needs re-turfing.",
    "lat": 28.539936,
    "lng": 77.284881,
    "mapUrl": "https://www.google.com/maps?q=28.539936,77.284881"
  },
  {
    "id": "lala-harydal-4",
    "parkId": "lala-harydal",
    "index": 4,
    "time": 5,
    "clip": 2,
    "type": "info",
    "title": "Lawn could use attention",
    "message": "Turf patchy around the formal beds — aerating and overseeding would help.",
    "lat": 28.540407,
    "lng": 77.286651,
    "mapUrl": "https://www.google.com/maps?q=28.540407,77.286651"
  },
  {
    "id": "lala-harydal-5",
    "parkId": "lala-harydal",
    "index": 5,
    "time": 27,
    "clip": 2,
    "type": "info",
    "title": "Canopy looking thin",
    "message": "Tree canopy a little sparse here — some watering would help.",
    "lat": 28.540661,
    "lng": 77.287295,
    "mapUrl": "https://www.google.com/maps?q=28.540661,77.287295"
  },
  {
    "id": "lala-harydal-6",
    "parkId": "lala-harydal",
    "index": 6,
    "time": 11,
    "clip": 3,
    "type": "info",
    "title": "Lawn could use attention",
    "message": "Grass thinning beside the axis — overseeding would bring it back.",
    "lat": 28.541085,
    "lng": 77.288228,
    "mapUrl": "https://www.google.com/maps?q=28.541085,77.288228"
  },
  {
    "id": "lala-harydal-7",
    "parkId": "lala-harydal",
    "index": 7,
    "time": 17,
    "clip": 3,
    "type": "info",
    "title": "A few bare patches",
    "message": "Some bare ground along the central axis — could do with re-turfing.",
    "lat": 28.541217,
    "lng": 77.288485,
    "mapUrl": "https://www.google.com/maps?q=28.541217,77.288485"
  },
  {
    "id": "smriti-van-mayur-vihar-1",
    "parkId": "smriti-van-mayur-vihar",
    "index": 1,
    "time": 3,
    "clip": 1,
    "type": "warning",
    "title": "Standing water observed",
    "message": "Water pooling in the planting bed — worth checking the drainage here.",
    "lat": 28.604802,
    "lng": 77.33723,
    "mapUrl": "https://www.google.com/maps?q=28.604802,77.337230"
  },
  {
    "id": "smriti-van-mayur-vihar-2",
    "parkId": "smriti-van-mayur-vihar",
    "index": 2,
    "time": 12,
    "clip": 1,
    "type": "info",
    "title": "Some litter about",
    "message": "A bit of loose debris across the bed — a sweep would tidy it up.",
    "lat": 28.604595,
    "lng": 77.337445,
    "mapUrl": "https://www.google.com/maps?q=28.604595,77.337445"
  },
  {
    "id": "smriti-van-mayur-vihar-3",
    "parkId": "smriti-van-mayur-vihar",
    "index": 3,
    "time": 17,
    "clip": 2,
    "type": "info",
    "title": "Fallen leaves piling up",
    "message": "Leaf litter accumulating across the play area — needs a good sweep before it gets slippery.",
    "lat": 28.60548,
    "lng": 77.338228,
    "mapUrl": "https://www.google.com/maps?q=28.605480,77.338228"
  },
  {
    "id": "smriti-van-mayur-vihar-4",
    "parkId": "smriti-van-mayur-vihar",
    "index": 4,
    "time": 25,
    "clip": 2,
    "type": "warning",
    "title": "Standing water observed",
    "message": "Water pooling in the play area — worth checking the drainage.",
    "lat": 28.605254,
    "lng": 77.338378,
    "mapUrl": "https://www.google.com/maps?q=28.605254,77.338378"
  },
  {
    "id": "smriti-van-mayur-vihar-5",
    "parkId": "smriti-van-mayur-vihar",
    "index": 5,
    "time": 40,
    "clip": 2,
    "type": "error",
    "title": "Play equipment broken — critical",
    "message": "Swing appears collapsed on the sand. Inspect and make safe before reopening.",
    "lat": 28.605066,
    "lng": 77.33855,
    "mapUrl": "https://www.google.com/maps?q=28.605066,77.338550"
  },
  {
    "id": "smriti-van-mayur-vihar-6",
    "parkId": "smriti-van-mayur-vihar",
    "index": 6,
    "time": 7,
    "clip": 3,
    "type": "warning",
    "title": "Standing water observed",
    "message": "Water lying across the open ground — worth a look at levels and drainage.",
    "lat": 28.605763,
    "lng": 77.339773,
    "mapUrl": "https://www.google.com/maps?q=28.605763,77.339773"
  },
  {
    "id": "smriti-van-mayur-vihar-7",
    "parkId": "smriti-van-mayur-vihar",
    "index": 7,
    "time": 10,
    "clip": 3,
    "type": "warning",
    "title": "Algae risk from stagnant water",
    "message": "Prolonged waterlogging could breed algae and mosquitoes — drainage needs urgent attention to prevent disease spread.",
    "lat": 28.605556,
    "lng": 77.339988,
    "mapUrl": "https://www.google.com/maps?q=28.605556,77.339988"
  },
  {
    "id": "smriti-van-mayur-vihar-8",
    "parkId": "smriti-van-mayur-vihar",
    "index": 8,
    "time": 14,
    "clip": 3,
    "type": "warning",
    "title": "Ground cover thinning",
    "message": "Ground is bare and compacted in places — decompacting and re-turfing would help.",
    "lat": 28.605349,
    "lng": 77.339537,
    "mapUrl": "https://www.google.com/maps?q=28.605349,77.339537"
  },
  {
    "id": "smriti-van-mayur-vihar-9",
    "parkId": "smriti-van-mayur-vihar",
    "index": 9,
    "time": 28,
    "clip": 3,
    "type": "info",
    "title": "Some litter about",
    "message": "A bit of loose debris across the open ground — worth a sweep.",
    "lat": 28.60516,
    "lng": 77.339322,
    "mapUrl": "https://www.google.com/maps?q=28.605160,77.339322"
  },
  {
    "id": "smriti-van-mayur-vihar-10",
    "parkId": "smriti-van-mayur-vihar",
    "index": 10,
    "time": 4,
    "clip": 4,
    "type": "info",
    "title": "A few bare patches",
    "message": "Some compacted ground along the path — could do with re-turfing.",
    "lat": 28.606517,
    "lng": 77.341168,
    "mapUrl": "https://www.google.com/maps?q=28.606517,77.341168"
  },
  {
    "id": "smriti-van-mayur-vihar-11",
    "parkId": "smriti-van-mayur-vihar",
    "index": 11,
    "time": 21,
    "clip": 4,
    "type": "info",
    "title": "Lawn could use attention",
    "message": "Grass thinning in patches — aerating and overseeding would bring it back.",
    "lat": 28.606234,
    "lng": 77.341382,
    "mapUrl": "https://www.google.com/maps?q=28.606234,77.341382"
  },
  {
    "id": "smriti-van-mayur-vihar-12",
    "parkId": "smriti-van-mayur-vihar",
    "index": 12,
    "time": 31,
    "clip": 4,
    "type": "info",
    "title": "Hedges need a trim",
    "message": "A few gaps showing along the shrub line — trimming and gap-filling would tidy it.",
    "lat": 28.606762,
    "lng": 77.341597,
    "mapUrl": "https://www.google.com/maps?q=28.606762,77.341597"
  },
  {
    "id": "r-block-asaf-ali-1",
    "parkId": "r-block-asaf-ali",
    "index": 1,
    "time": 6,
    "clip": 1,
    "type": "info",
    "title": "Hedges need a trim",
    "message": "Shrub line growing uneven under the canopy — trimming would tidy it.",
    "lat": 28.546999,
    "lng": 77.242318,
    "mapUrl": "https://www.google.com/maps?q=28.546999,77.242318"
  },
  {
    "id": "r-block-asaf-ali-2",
    "parkId": "r-block-asaf-ali",
    "index": 2,
    "time": 35,
    "clip": 1,
    "type": "info",
    "title": "Lawn could use attention",
    "message": "Grass thinning in places — overseeding would bring it back.",
    "lat": 28.54632,
    "lng": 77.241277,
    "mapUrl": "https://www.google.com/maps?q=28.546320,77.241277"
  },
  {
    "id": "r-block-asaf-ali-3",
    "parkId": "r-block-asaf-ali",
    "index": 3,
    "time": 4,
    "clip": 2,
    "type": "warning",
    "title": "Pavilion structure deteriorating",
    "message": "Infrastructure showing signs of wear — cracks and peeling visible on the building.",
    "lat": 28.545774,
    "lng": 77.240988,
    "mapUrl": "https://www.google.com/maps?q=28.545774,77.240988"
  },
  {
    "id": "r-block-asaf-ali-4",
    "parkId": "r-block-asaf-ali",
    "index": 4,
    "time": 22,
    "clip": 2,
    "type": "info",
    "title": "Some dry vegetation",
    "message": "Patches of dry growth near the pavilion — a watering round would help.",
    "lat": 28.545585,
    "lng": 77.241245,
    "mapUrl": "https://www.google.com/maps?q=28.545585,77.241245"
  },
  {
    "id": "r-block-asaf-ali-5",
    "parkId": "r-block-asaf-ali",
    "index": 5,
    "time": 34,
    "clip": 2,
    "type": "warning",
    "title": "Building needs repair",
    "message": "Pavilion exterior in poor condition — repainting and structural repair recommended.",
    "lat": 28.545925,
    "lng": 77.241073,
    "mapUrl": "https://www.google.com/maps?q=28.545925,77.241073"
  },
  {
    "id": "vasant-udyan-1",
    "parkId": "vasant-udyan",
    "index": 1,
    "time": 4,
    "clip": 1,
    "type": "warning",
    "title": "Play area flooring damaged",
    "message": "Tiles and floor surface in the children's play area are cracked and broken — repair needed for safety.",
    "lat": 28.558689,
    "lng": 77.164823,
    "mapUrl": "https://www.google.com/maps?q=28.558689,77.164823"
  },
  {
    "id": "vasant-udyan-2",
    "parkId": "vasant-udyan",
    "index": 2,
    "time": 10,
    "clip": 1,
    "type": "info",
    "title": "Some litter about",
    "message": "Loose debris scattered across the area — a good sweep would tidy things up.",
    "lat": 28.558501,
    "lng": 77.165187,
    "mapUrl": "https://www.google.com/maps?q=28.558501,77.165187"
  },
  {
    "id": "vasant-udyan-3",
    "parkId": "vasant-udyan",
    "index": 3,
    "time": 24,
    "clip": 1,
    "type": "info",
    "title": "A few bare patches",
    "message": "Bare, compacted ground under the equipment — could do with re-turfing.",
    "lat": 28.558312,
    "lng": 77.165402,
    "mapUrl": "https://www.google.com/maps?q=28.558312,77.165402"
  },
  {
    "id": "vasant-udyan-4",
    "parkId": "vasant-udyan",
    "index": 4,
    "time": 33,
    "clip": 1,
    "type": "info",
    "title": "Lawn could use attention",
    "message": "Grass thinning around the edges — aerating and overseeding would help.",
    "lat": 28.558218,
    "lng": 77.164973,
    "mapUrl": "https://www.google.com/maps?q=28.558218,77.164973"
  },
  {
    "id": "vasant-udyan-5",
    "parkId": "vasant-udyan",
    "index": 5,
    "time": 4,
    "clip": 2,
    "type": "warning",
    "title": "Ground cover thinning",
    "message": "Bare, compacted ground along the path — decompacting and re-turfing would help.",
    "lat": 28.557182,
    "lng": 77.166367,
    "mapUrl": "https://www.google.com/maps?q=28.557182,77.166367"
  },
  {
    "id": "vasant-udyan-6",
    "parkId": "vasant-udyan",
    "index": 6,
    "time": 11,
    "clip": 2,
    "type": "warning",
    "title": "Path surface worn",
    "message": "Walking track showing wear along this stretch — worth patching.",
    "lat": 28.556899,
    "lng": 77.166582,
    "mapUrl": "https://www.google.com/maps?q=28.556899,77.166582"
  },
  {
    "id": "vasant-udyan-7",
    "parkId": "vasant-udyan",
    "index": 7,
    "time": 18,
    "clip": 2,
    "type": "info",
    "title": "Hedges need a trim",
    "message": "Gaps showing along the shrub line — trimming and gap-filling would tidy it.",
    "lat": 28.556729,
    "lng": 77.166153,
    "mapUrl": "https://www.google.com/maps?q=28.556729,77.166153"
  },
  {
    "id": "vasant-vatika-1",
    "parkId": "vasant-vatika",
    "index": 1,
    "time": 3,
    "clip": 1,
    "type": "warning",
    "title": "Shrubs showing wear",
    "message": "Hedge condition dipping near the fountain — gaps and thinning visible.",
    "lat": 28.53384,
    "lng": 77.146001,
    "mapUrl": "https://www.google.com/maps?q=28.533840,77.146001"
  },
  {
    "id": "vasant-vatika-2",
    "parkId": "vasant-vatika",
    "index": 2,
    "time": 3,
    "clip": 2,
    "type": "warning",
    "title": "Litter building up",
    "message": "Ground litter detected along the avenue — condition at 36%, needs attention.",
    "lat": 28.53531,
    "lng": 77.146795,
    "mapUrl": "https://www.google.com/maps?q=28.535310,77.146795"
  },
  {
    "id": "vasant-vatika-3",
    "parkId": "vasant-vatika",
    "index": 3,
    "time": 14,
    "clip": 2,
    "type": "warning",
    "title": "Hedges degrading",
    "message": "Multiple shrub lines showing poor condition — trimming and gap-filling recommended.",
    "lat": 28.536065,
    "lng": 77.147224,
    "mapUrl": "https://www.google.com/maps?q=28.536065,77.147224"
  },
  {
    "id": "vasant-vatika-4",
    "parkId": "vasant-vatika",
    "index": 4,
    "time": 35,
    "clip": 2,
    "type": "warning",
    "title": "Bare patches and dry vegetation",
    "message": "Compacted ground and dry vegetation cluster detected — irrigation review needed.",
    "lat": 28.534745,
    "lng": 77.146495,
    "mapUrl": "https://www.google.com/maps?q=28.534745,77.146495"
  },
  {
    "id": "vasant-vatika-5",
    "parkId": "vasant-vatika",
    "index": 5,
    "time": 3,
    "clip": 3,
    "type": "info",
    "title": "Ground wearing thin",
    "message": "Some bare patches visible near the gym area — minor re-turfing would help.",
    "lat": 28.532671,
    "lng": 77.145293,
    "mapUrl": "https://www.google.com/maps?q=28.532671,77.145293"
  },
  {
    "id": "vasant-vatika-6",
    "parkId": "vasant-vatika",
    "index": 6,
    "time": 16,
    "clip": 3,
    "type": "warning",
    "title": "Bare patches spreading",
    "message": "Exposed ground expanding across the hedge bed zone — needs soil treatment and re-seeding.",
    "lat": 28.532294,
    "lng": 77.144864,
    "mapUrl": "https://www.google.com/maps?q=28.532294,77.144864"
  },
  {
    "id": "vasant-vatika-7",
    "parkId": "vasant-vatika",
    "index": 7,
    "time": 40,
    "clip": 3,
    "type": "error",
    "title": "Ground condition critical",
    "message": "Bare ground at 6% condition — worst finding in this survey. Immediate action required.",
    "lat": 28.532011,
    "lng": 77.144606,
    "mapUrl": "https://www.google.com/maps?q=28.532011,77.144606"
  },
  {
    "id": "vasant-vatika-8",
    "parkId": "vasant-vatika",
    "index": 8,
    "time": 55,
    "clip": 3,
    "type": "warning",
    "title": "Path surface degrading",
    "message": "Walking track wearing thin at the far end — resurfacing recommended.",
    "lat": 28.531729,
    "lng": 77.144349,
    "mapUrl": "https://www.google.com/maps?q=28.531729,77.144349"
  }
];

export const anomaliesForPark = (parkId: string): Anomaly[] =>
  ANOMALIES.filter((a) => a.parkId === parkId);

/** The still for a finding, or undefined if none was extracted. */
export const frameFor = (id: string) => ANOMALY_FRAMES[id];

/** mm:ss, for showing where in the recording a finding was raised. */
export const formatAnomalyTime = (seconds: number): string => {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
};
